// Threads echo bot — reference implementation, typed against the OpenAPI spec.
//
// Two integration surfaces:
//   1. WebSocket  GET /ws/:channelId        — receive live channel events, and send
//      lightweight signals (typing_start/typing_stop, ping). One socket per channel.
//   2. REST       POST /messages/:id/replies, /messages/:id/reactions,
//      /channels/:id/read, /bots/self/capabilities; GET /channels, /dms — create
//      durable state and discover where to listen.
//
// Request/response shapes are imported from the generated spec types (see the `import
// type` block) so a wrong field name or message_type fails `npm run typecheck`. The bot
// is *run* with tsx, which strips types without checking — so `npm start` works even
// before the (gitignored) generated types exist; only `npm run typecheck` needs them.
//
// Run with: npm start   (env loaded from ../.env). See .env.example for the required
// variables.
import process from 'node:process';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { createServer } from 'node:http';
import { createHmac, timingSafeEqual } from 'node:crypto';
import WebSocket from 'ws';

// --- Spec types -------------------------------------------------------------
// Generated by `npm run gen-types` (openapi-typescript) from api/openapi/*.yaml.
// These are type-only imports: tsx erases them at runtime, so a missing file only
// breaks `npm run typecheck`, never `npm start`.
import type { components } from '../../../api/generated/types/threads';
import type { components as WsComponents } from '../../../api/generated/types/ws-events';

type Schemas = components['schemas'];
type WsSchemas = WsComponents['schemas'];

// REST request/response bodies, straight from the spec.
type SendMessageRequest = Schemas['SendMessageRequest'];
type AddReactionRequest = Schemas['AddReactionRequest'];
type UpdateSelfCapabilitiesRequest = Schemas['UpdateSelfCapabilitiesRequest'];
type Message = Schemas['Message'];
type MessageType = Schemas['MessageType'];
type ChannelListItem = Schemas['ChannelListItem'];
type DMChannel = Schemas['DMChannel'];

// WebSocket events. Caveat: openapi-typescript rewrites each event's `type` to the
// *schema name* ("MessageEvent") as a synthetic discriminator, but the value actually
// on the wire is the OpenAPI `const` ("message"). Re-map the events we narrow on so the
// runtime check (`type === 'message'`) and the static type agree. `Wire<S, T>` does the
// remap: take the generated schema S, drop its bogus discriminator, pin the real one.
type Wire<S, T extends string> = Omit<S, 'type'> & { type: T };
type MessageEvent = Wire<WsSchemas['MessageEvent'], 'message'>;
type ReactionAddedEvent = Wire<WsSchemas['ReactionAddedEvent'], 'reaction_added'>;
type MemberAddedEvent = Wire<WsSchemas['MemberAddedEvent'], 'member_added'>;
type MemberRemovedEvent = Wire<WsSchemas['MemberRemovedEvent'], 'member_removed'>;
type ChannelArchivedEvent = Wire<WsSchemas['ChannelArchivedEvent'], 'channel_archived'>;
type ChannelDeletedEvent = Wire<WsSchemas['ChannelDeletedEvent'], 'channel_deleted'>;
// The yaml schema is named `removed_event`; its `const` type is bot_restart_requested.
type RestartRequestedEvent = Wire<WsSchemas['removed_event'], 'bot_restart_requested'>;
// Cooperative cancellation: Threads emits this (over WS *and* webhook) when a human
// cancels a process this bot created. The bot is expected to stop the matching run.
type ProcessKillEvent = Wire<WsSchemas['ProcessKillEvent'], 'process_kill'>;
type ActionResultEvent = Wire<WsSchemas['ActionResultEvent'], 'action_result'>;
type ActionErrorEvent = Wire<WsSchemas['ActionErrorEvent'], 'action_error'>;
// Presence socket (GET /ws/presence) events.
type PresenceSnapshotEvent = Wire<WsSchemas['PresenceSnapshotEvent'], 'presence_snapshot'>;
type PresenceUpdateEvent = Wire<WsSchemas['PresenceUpdateEvent'], 'presence_update'>;

// Outbound socket signals. We hand-write these unions rather than reuse the generated
// *ClientEvent* types for the same discriminator reason: their `type` is rewritten to
// the schema name, not the wire value.
//   - signals are fire-and-forget (no reply expected);
//   - actions carry an actionId and are answered with action_result / action_error.
type WsSignal = { type: 'typing_start' } | { type: 'typing_stop' } | { type: 'ping' };
type WsActionRequest =
  | { type: 'reaction.add'; messageId: string; emoji: string }
  | { type: 'message.create'; channelId: string; content: string; threadId?: string | null; message_type?: MessageType };

// --- Config -----------------------------------------------------------------
// Load ../.env (no dependency) unless the vars are already in the environment.
loadDotEnv();

const API_URL = required('THREADS_API_URL');
const BOT_TOKEN = required('THREADS_BOT_TOKEN');
const BOT_USER_ID = required('THREADS_BOT_USER_ID');
const BOT_USERNAME = required('THREADS_BOT_USERNAME');

// Channels are auto-discovered (see syncSubscriptions). These optional env vars name
// extra channels to also subscribe to — handy to pin a specific channel id. Accepts a
// single id (THREADS_CHANNEL_ID) or a comma-separated list (THREADS_CHANNEL_IDS).
const EXPLICIT_CHANNELS = (process.env.THREADS_CHANNEL_IDS ?? process.env.THREADS_CHANNEL_ID ?? '')
  .split(',')
  .map((s) => s.trim())
  .filter(Boolean);

const WS_BASE = API_URL.replace(/^http/, 'ws'); // https→wss, http→ws
const AUTH = { Authorization: `Bearer ${BOT_TOKEN}` };

// How often to re-discover channels/DMs, so the bot picks up a channel it was just
// added to or a DM a human just opened (neither arrives on a socket it already holds).
const DISCOVERY_INTERVAL_MS = 30_000;

// Remember message ids we have already acted on. Reconnects re-deliver nothing,
// but a defensive dedup set keeps us idempotent if the bot is restarted mid-stream.
const handled = new Set<string>();

// Ids of messages this bot authored, so it can tell when a human reacts to *its* output
// (the reaction-mirror trigger). Both this and `handled` grow unbounded; a long-running
// bot would cap them (e.g. an LRU) — fine to keep simple for a reference.
const myMessages = new Set<string>();

// --- Process runs -----------------------------------------------------------
// A "process" is one turn this bot is working on. The bot creates it (POST /processes)
// when it starts, reports activity/status over REST, and finishes it as done — UNLESS a
// human cancels it from Threads, which arrives as a process_kill event (over the channel
// WebSocket and, if configured, the webhook receiver below). On cancel we flip
// `cancelled` and wake the in-flight wait so the turn stops without posting an answer.
interface InflightRun {
  processId: string;
  channelId: string;
  cancelled: boolean;
  wake: () => void; // resolves the current abortable wait early
}
const runs = new Map<string, InflightRun>(); // processId -> run

function markCancelled(processId: string): void {
  const run = runs.get(processId);
  if (!run || run.cancelled) return;
  run.cancelled = true;
  run.wake();
  console.log(`[proc] cancel received for ${processId}`);
}

// sleep that returns early if the run is cancelled. Resolves true if it slept the full
// duration, false if it was woken by a cancel.
function abortableSleep(ms: number, run: InflightRun | null): Promise<boolean> {
  return new Promise((resolve) => {
    if (run?.cancelled) return resolve(false);
    const timer = setTimeout(() => resolve(true), ms);
    if (run) {
      run.wake = () => {
        clearTimeout(timer);
        resolve(false);
      };
    }
  });
}

// --- REST helper ------------------------------------------------------------
// Every REST call carries the bot's Bearer token. Returns the parsed JSON body typed
// as T, or throws with the status + body text so callers can log a useful error.
async function api<T = unknown>(method: string, path: string, body?: unknown): Promise<T> {
  const res = await fetch(`${API_URL}${path}`, {
    method,
    headers: { ...AUTH, ...(body !== undefined ? { 'Content-Type': 'application/json' } : {}) },
    body: body !== undefined ? JSON.stringify(body) : undefined,
  });
  if (!res.ok) {
    throw new Error(`${method} ${path} → ${res.status} ${await res.text()}`);
  }
  // Some endpoints (mark-read) return an empty body; tolerate that.
  return (res.status === 204 ? null : await res.json().catch(() => null)) as T;
}

// --- Capabilities -----------------------------------------------------------
// On startup, advertise what this bot can do. `dm_allowed_usernames` opts specific humans
// into DMing the bot. (A bot that exposed selectable models would also send a `models`
// array — the client renders that as a DM model picker — but an echo bot has none, so we
// omit it. The endpoint replaces the whole capabilities object, so this also clears any
// `models` a previous run may have stored.) Self-scoped: POST /bots/self/capabilities.
async function advertiseCapabilities(): Promise<void> {
  const body: UpdateSelfCapabilitiesRequest = {
    // Let the seeded `dan` user DM the bot. Admins can DM any bot without being
    // listed here; this opts specific non-admin humans in — add usernames you want
    // to grant DM access to.
    dm_allowed_usernames: ['dan'],
  };
  try {
    await api('POST', '/bots/self/capabilities', body);
    console.log('[caps] advertised capabilities (dm_allowed=[dan])');
  } catch (err) {
    console.warn('[caps] could not advertise capabilities:', errMsg(err));
  }
}

// --- Channel discovery ------------------------------------------------------
// A bot listens to every channel it belongs to: regular channels via GET /channels
// (excludes DMs) and direct messages via GET /dms. Union them with any EXPLICIT_CHANNELS.
interface ChannelTarget {
  isDm: boolean;
  // The channel's auto-respond bot (null for none/DMs). Lets the bot tell whether a
  // channel routes to it without an @mention — needed by the backfill path, since
  // REST message rows don't carry the per-broadcast `autoRespondBotId` the WS adds.
  autoRespondBotId: string | null;
}

async function discoverChannels(): Promise<{ id: string; isDm: boolean; autoRespondBotId: string | null }[]> {
  const [channels, dms] = await Promise.all([
    api<ChannelListItem[]>('GET', '/channels').catch((e) => {
      console.warn('[sync] GET /channels failed:', errMsg(e));
      return [] as ChannelListItem[];
    }),
    api<DMChannel[]>('GET', '/dms').catch((e) => {
      console.warn('[sync] GET /dms failed:', errMsg(e));
      return [] as DMChannel[];
    }),
  ]);

  const targets = new Map<string, ChannelTarget>(); // id -> target, first writer wins
  for (const id of EXPLICIT_CHANNELS) if (!targets.has(id)) targets.set(id, { isDm: false, autoRespondBotId: null });
  for (const c of channels) {
    if (c.id && !targets.has(c.id)) {
      const autoRespondBotId = (c as { auto_respond_bot_id?: string | null }).auto_respond_bot_id ?? null;
      targets.set(c.id, { isDm: false, autoRespondBotId });
    }
  }
  for (const d of dms) if (d.id && !targets.has(d.id)) targets.set(d.id, { isDm: true, autoRespondBotId: null });
  return [...targets].map(([id, t]) => ({ id, ...t }));
}

// Open a connection to every newly-discovered channel. Existing connections are left
// alone; teardown on leave/archive is handled by the event router (see Batch 3).
//
// `backfill` is set for runtime re-discovery (a channel/DM the bot was just added to):
// those connections catch up on messages sent before the socket opened. The initial
// startup sweep passes backfill=false so a restart doesn't re-echo old history.
async function syncSubscriptions(opts: { backfill?: boolean } = {}): Promise<void> {
  let opened = 0;
  for (const { id, isDm, autoRespondBotId } of await discoverChannels()) {
    if (!conns.has(id)) {
      ensureConn(id, isDm, autoRespondBotId, opts.backfill ?? false);
      opened++;
    }
  }
  if (opened) console.log(`[sync] subscribed to ${opened} new channel(s); ${conns.size} total`);
}

// --- WebSocket lifecycle (one connection per channel) -----------------------
interface Conn {
  channelId: string;
  isDm: boolean;
  autoRespondBotId: string | null; // channel's auto-respond bot, if any
  backfillOnConnect: boolean; // catch up on missed messages the first time this socket opens
  ws?: WebSocket;
  reconnectDelay: number; // grows to a cap on repeated failures
  keepalive?: ReturnType<typeof setInterval>;
  closed: boolean; // set on graceful shutdown/teardown to stop the reconnect loop
}

const conns = new Map<string, Conn>();

function ensureConn(channelId: string, isDm: boolean, autoRespondBotId: string | null = null, backfill = false): void {
  if (conns.has(channelId)) return;
  const conn: Conn = { channelId, isDm, autoRespondBotId, backfillOnConnect: backfill, reconnectDelay: 1000, closed: false };
  conns.set(channelId, conn);
  connect(conn);
}

function connect(conn: Conn): void {
  const label = conn.isDm ? `dm:${conn.channelId}` : conn.channelId;
  console.log(`[ws] connecting to ${label}`);
  const sock = new WebSocket(`${WS_BASE}/ws/${conn.channelId}`, { headers: AUTH });
  conn.ws = sock;

  sock.on('open', () => {
    conn.reconnectDelay = 1000;
    console.log(`[ws] connected: ${label}`);
    // App-level keepalive. Protocol ping/pong is unreliable through CF's edge,
    // so the server speaks JSON {type:"ping"} -> {type:"pong"}.
    clearInterval(conn.keepalive);
    conn.keepalive = setInterval(() => wsSend(conn, { type: 'ping' }), 30_000);
    // Just joined this channel: replay the recent backlog once to catch a message
    // sent in the gap before this socket opened (WS carries only future events).
    if (conn.backfillOnConnect) {
      conn.backfillOnConnect = false; // once only — reconnects must not re-replay
      backfillOnJoin(conn).catch((e) => console.warn('[backfill]', errMsg(e)));
    }
  });

  sock.on('message', (raw: WebSocket.RawData) => {
    let frame: unknown;
    try {
      frame = JSON.parse(raw.toString());
    } catch {
      return; // ignore non-JSON frames
    }
    if (frame && typeof frame === 'object') {
      route(conn, frame as Record<string, unknown>).catch((err) => console.error('[handler] error', err));
    }
  });

  sock.on('close', (code: number) => {
    clearInterval(conn.keepalive);
    if (conn.closed) return; // intentional shutdown — don't reconnect
    console.warn(`[ws] closed ${label} (${code}); reconnecting in ${conn.reconnectDelay}ms`);
    setTimeout(() => connect(conn), conn.reconnectDelay);
    conn.reconnectDelay = Math.min(conn.reconnectDelay * 2, 30_000); // exponential backoff
  });

  sock.on('error', (err: Error) => {
    console.error(`[ws] error ${label}:`, err.message);
    // 'close' fires after 'error' and drives the reconnect.
  });
}

// Send a lightweight signal up a channel's socket if it is open (fire-and-forget).
function wsSend(conn: Conn, signal: WsSignal): void {
  if (conn.ws?.readyState === WebSocket.OPEN) conn.ws.send(JSON.stringify(signal));
}

// Tear a connection down for good (bot removed from the channel, or channel
// archived/deleted). Unlike a close-with-reconnect, this stops the reconnect loop and
// forgets the channel so it isn't reopened — though a channel pinned in EXPLICIT_CHANNELS
// will be retried on the next discovery sweep.
function teardown(channelId: string, reason: string): void {
  const conn = conns.get(channelId);
  if (!conn) return;
  console.log(`[ws] tearing down ${channelId} (${reason})`);
  conn.closed = true;
  clearInterval(conn.keepalive);
  conn.ws?.close();
  conns.delete(channelId);
}

// --- WebSocket actions (request/response over the socket) -------------------
// Besides fire-and-forget signals, the socket accepts *actions* that create durable
// state — message.create and reaction.add — the same things you can do over REST. Each
// carries an `actionId`; the server answers with action_result or action_error bearing
// the same id. wsAction() sends one and resolves/rejects when that ack arrives.
//
// REST vs WS for sends: REST is simpler and returns the created row directly (we use it
// for replies). The WS path saves a round-trip when you're already holding the socket
// and want an ack — we use it below for the reaction mirror and the welcome message, to
// exercise both surfaces.
let actionSeq = 0;
const pendingActions = new Map<string, { resolve: (v: unknown) => void; reject: (e: Error) => void; timer: ReturnType<typeof setTimeout> }>();

function wsAction(conn: Conn, action: WsActionRequest): Promise<unknown> {
  const actionId = `act-${++actionSeq}`;
  return new Promise<unknown>((resolve, reject) => {
    if (conn.ws?.readyState !== WebSocket.OPEN) {
      reject(new Error(`socket for ${conn.channelId} is not open`));
      return;
    }
    const timer = setTimeout(() => {
      pendingActions.delete(actionId);
      reject(new Error(`action ${action.type} timed out`));
    }, 10_000);
    pendingActions.set(actionId, { resolve, reject, timer });
    conn.ws.send(JSON.stringify({ ...action, actionId }));
  });
}

// Resolve the pending wsAction() that matches an incoming action_result/action_error.
function onActionAck(frame: ActionResultEvent | ActionErrorEvent): void {
  const actionId = frame.actionId;
  if (typeof actionId !== 'string') return;
  const pending = pendingActions.get(actionId);
  if (!pending) return;
  pendingActions.delete(actionId);
  clearTimeout(pending.timer);
  if (frame.type === 'action_error') {
    pending.reject(new Error(`action_error ${frame.status}: ${JSON.stringify(frame.error)}`));
  } else {
    pending.resolve(frame.result);
  }
}

// --- Presence ---------------------------------------------------------------
// A second, channel-independent socket: GET /ws/presence. Just holding it open marks the
// bot **online** (the green dot in the UI); the events it pushes let the bot track who
// else is online. Note the keepalive runs the *opposite* way from channel sockets — here
// the server sends {type:"ping"} and the bot must reply {type:"pong"}, or it's dropped
// after a couple of missed beats.
const online = new Set<string>(); // userIds currently online (others, not the bot itself)
let presenceWs: WebSocket | undefined;
let presenceReconnectDelay = 1000;
let presenceClosed = false;
let presenceKeepalive: ReturnType<typeof setInterval> | undefined;

function connectPresence(): void {
  console.log('[presence] connecting');
  const sock = new WebSocket(`${WS_BASE}/ws/presence`, { headers: AUTH });
  presenceWs = sock;

  sock.on('open', () => {
    presenceReconnectDelay = 1000;
    console.log('[presence] online');
    // Our own keepalive: the server auto-responds {type:"pong"} without waking the room,
    // which lets us notice a half-open socket. (Separate from answering the server's own
    // {type:"ping"} heartbeat below — both directions run on this socket.)
    clearInterval(presenceKeepalive);
    presenceKeepalive = setInterval(() => {
      if (sock.readyState === WebSocket.OPEN) sock.send(JSON.stringify({ type: 'ping' }));
    }, 30_000);
  });

  sock.on('message', (raw: WebSocket.RawData) => {
    let frame: unknown;
    try {
      frame = JSON.parse(raw.toString());
    } catch {
      return;
    }
    if (frame && typeof frame === 'object') routePresence(frame as Record<string, unknown>);
  });

  sock.on('close', (code: number) => {
    clearInterval(presenceKeepalive);
    if (presenceClosed) return;
    online.clear();
    console.warn(`[presence] closed (${code}); reconnecting in ${presenceReconnectDelay}ms`);
    setTimeout(connectPresence, presenceReconnectDelay);
    presenceReconnectDelay = Math.min(presenceReconnectDelay * 2, 30_000);
  });

  sock.on('error', (err: Error) => console.error('[presence] error', err.message));
}

function routePresence(frame: Record<string, unknown>): void {
  switch (frame.type) {
    case 'ping':
      // Server heartbeat — must answer to stay connected (and counted as online).
      if (presenceWs?.readyState === WebSocket.OPEN) presenceWs.send(JSON.stringify({ type: 'pong' }));
      return;
    case 'presence_snapshot': {
      // Initial set of who's online (the server omits the bot itself).
      const snap = frame as PresenceSnapshotEvent;
      online.clear();
      for (const [userId, isOnline] of Object.entries(snap.users ?? {})) {
        if (isOnline) online.add(userId);
      }
      console.log(`[presence] snapshot: ${online.size} online`);
      return;
    }
    case 'presence_update': {
      const upd = frame as PresenceUpdateEvent;
      if (upd.online) online.add(upd.userId);
      else online.delete(upd.userId);
      console.log(`[presence] ${upd.userId} ${upd.online ? 'online' : 'offline'} (${online.size} online)`);
      return;
    }
  }
}

// `online` (the userIds currently connected, the bot excluded) is now available for
// presence-aware behaviour — e.g. only @mention a human in a reply when they're online,
// or answer now vs. leave a note for later.

// --- Event handling ---------------------------------------------------------
// The channel stream carries many event types. Dispatch on the wire `type` and handle
// the ones this bot cares about; everything else (typing, pong, presence, …) is ignored.
async function route(conn: Conn, frame: Record<string, unknown>): Promise<void> {
  switch (frame.type) {
    case 'message':
      return onMessage(conn, frame as MessageEvent);
    case 'reaction_added':
      return onReactionAdded(conn, frame as ReactionAddedEvent);
    case 'member_added':
      return onMemberAdded(conn, frame as MemberAddedEvent);
    case 'member_removed':
      return onMemberRemoved(conn, frame as MemberRemovedEvent);
    case 'channel_archived':
    case 'channel_deleted':
      return onChannelGone(conn, frame as ChannelArchivedEvent | ChannelDeletedEvent);
    case 'bot_restart_requested':
      return onRestartRequested(frame as RestartRequestedEvent);
    case 'process_kill':
      markCancelled((frame as ProcessKillEvent).processId);
      return;
    case 'action_result':
    case 'action_error':
      return onActionAck(frame as ActionResultEvent | ActionErrorEvent);
  }
}

// Catch-up for a freshly-joined channel/DM. The WebSocket only delivers events that
// occur after the socket opens, so the first message in a brand-new ephemeral channel
// (or a just-opened DM) arrives before the bot is listening and is otherwise lost.
// Fetch the recent backlog and run the latest unanswered human message through the
// normal handler. `handled` dedup means anything the live socket already delivered is
// skipped, so there's no double reply.
async function backfillOnJoin(conn: Conn): Promise<void> {
  const page = await api<{ messages: MessageEvent[] }>('GET', `/channels/${conn.channelId}/messages?limit=10`);
  const messages = page?.messages ?? [];
  // Walk newest→oldest. The first bot message means the latest exchange was already
  // answered — nothing to catch up on. Otherwise replay the most recent human message.
  for (let i = messages.length - 1; i >= 0; i--) {
    const m = messages[i];
    if (m.userId === BOT_USER_ID) return;
    if (m.messageType && m.messageType !== 'human') continue;
    // REST rows lack the per-broadcast autoRespondBotId; stamp it from the channel so
    // onMessage's auto-route check behaves exactly as it would for a live event.
    await onMessage(conn, { ...m, autoRespondBotId: conn.autoRespondBotId } as MessageEvent);
    return;
  }
}

async function onMessage(conn: Conn, event: MessageEvent): Promise<void> {
  // 1. Never react to our own output (prevents infinite loops).
  if (event.userId === BOT_USER_ID) return;

  // 2. Only react to human chat by default. Bots also emit progress/tool/thinking
  //    traces; ignore those unless you explicitly handle them.
  if (event.messageType && event.messageType !== 'human') return;

  // 3. Dedup.
  if (handled.has(event.id)) return;

  // 4. Decide whether this message is for us:
  //    - in a DM, every human message is implicitly addressed to the bot, or
  //    - in a channel, we're @mentioned, or the channel auto-routes to this bot.
  const mentioned = event.mentions?.some(
    (m) => m.userId === BOT_USER_ID || m.username === BOT_USERNAME,
  );
  const autoRouted = event.autoRespondBotId === BOT_USER_ID;
  if (!conn.isDm && !mentioned && !autoRouted) return;

  handled.add(event.id);
  console.log(`[msg] (${conn.isDm ? 'dm' : event.channelId}) ${event.username}: ${event.content}`);

  await respond(conn, event);
}

// Reaction trigger: when a human reacts to one of *our own* messages, mirror the emoji
// back as an acknowledgement. Sent over the WebSocket (reaction.add action) to exercise
// that path; same self-ignore + idempotency rules as any other trigger.
async function onReactionAdded(conn: Conn, event: ReactionAddedEvent): Promise<void> {
  if (event.userId === BOT_USER_ID) return; // our own reaction — ignore
  if (!myMessages.has(event.messageId)) return; // only mirror reactions on our messages
  try {
    await wsAction(conn, { type: 'reaction.add', messageId: event.messageId, emoji: event.emoji });
    console.log(`[reaction] mirrored ${event.emoji} from ${event.username}`);
  } catch (err) {
    console.warn('[reaction] mirror failed:', errMsg(err));
  }
}

// Greet a human who joins a channel the bot is in. Posted with message.create over the
// socket (the other WS action). DMs have no members, and we skip the bot being added to
// itself — discovery handles that.
async function onMemberAdded(conn: Conn, event: MemberAddedEvent): Promise<void> {
  // The bot itself was added to a channel (e.g. a new ephemeral channel auto-adds it).
  // This event arrives on an *existing* socket, not the new channel's — so kick off
  // discovery now to connect (with backfill) instead of waiting for the next poll.
  // Cuts the join→first-reply latency from up to DISCOVERY_INTERVAL_MS to ~immediate.
  if (event.targetUserId === BOT_USER_ID) {
    syncSubscriptions({ backfill: true }).catch((e) => console.warn('[sync]', errMsg(e)));
    return;
  }
  // Member events carry their own channelId and may be delivered on more than one of the
  // bot's sockets — only act for the channel this connection owns.
  if (event.channelId !== conn.channelId) return;
  if (conn.isDm) return;
  try {
    await wsAction(conn, { type: 'message.create', channelId: conn.channelId, content: `👋 Welcome, @${event.username ?? 'there'}!` });
    console.log(`[greet] welcomed ${event.username ?? event.targetUserId}`);
  } catch (err) {
    console.warn('[greet] failed:', errMsg(err));
  }
}

// If the bot itself is removed from a channel, stop listening to it. The server delivers
// this (target = the bot) on *every* socket the bot holds, so match channelId to tear
// down only the right one rather than all of them.
function onMemberRemoved(conn: Conn, event: MemberRemovedEvent): void {
  if (event.channelId !== conn.channelId) return;
  if (event.targetUserId === BOT_USER_ID) teardown(conn.channelId, 'removed from channel');
}

// A channel the bot is in was archived or deleted — same channelId guard, then stop
// listening to it.
function onChannelGone(conn: Conn, event: ChannelArchivedEvent | ChannelDeletedEvent): void {
  if (event.channelId !== conn.channelId) return;
  teardown(conn.channelId, event.type);
}

// An admin asked the bot to restart (e.g. to pick up new config). Do a soft restart:
// drop every connection and re-bootstrap. A production bot might instead process.exit(0)
// and let its supervisor relaunch to load new *code*. The event is delivered on every
// channel socket, so `restarting` debounces the duplicates.
let restarting = false;
async function onRestartRequested(event: RestartRequestedEvent): Promise<void> {
  if (restarting) return;
  restarting = true;
  console.log(`[restart] requested by ${event.requestedByUsername ?? event.requestedBy}${event.reason ? `: ${event.reason}` : ''}`);
  for (const conn of conns.values()) {
    conn.closed = true;
    clearInterval(conn.keepalive);
    conn.ws?.close();
  }
  conns.clear();
  handled.clear();
  await cleanupInterruptedRuns();
  await advertiseCapabilities();
  await syncSubscriptions();
  restarting = false;
}

// The full "engagement" lifecycle a Threads bot can present to a human:
//   acknowledge → show work → answer → tidy up.
// For an echo bot the "work" is instant; a real agent fills the same beats while a
// model streams. Each step is independent — keep the ones that fit your UX.
async function respond(conn: Conn, event: MessageEvent): Promise<void> {
  // (a) Acknowledge immediately with a reaction so the sender sees we received it,
  //     even before the answer is ready.
  await react(event.id, '👀').catch((e) => console.warn('[react]', errMsg(e)));

  // (b) Register a process so this turn shows up on Threads' process page and can be
  //     cancelled mid-flight. The deliberate "thinking" delay below is the cancellation
  //     window: a human hitting Cancel sends process_kill, which wakes the wait early.
  const run = await startRun(event.channelId, event.id);

  // (c) Show a typing indicator while composing. typing_* are WebSocket-only signals
  //     and auto-expire server-side, so a crash can't leave the bot "typing" forever.
  wsSend(conn, { type: 'typing_start' });

  // Where does the answer go? Directly in the channel by default; in a thread only when
  // the sender's message contains the word "thread".
  const useThread = /\bthread\b/i.test(event.content);

  // A message containing "long" makes the turn deliberately slow (10s) so there's a wide
  // window to exercise cancellation from the Threads process page; otherwise it's 1-3s.
  const thinkMs = /\blong\b/i.test(event.content) ? 10_000 : 1000 + Math.random() * 2000;

  try {
    if (useThread) {
      // (d) Optionally stream progress. Threads models the lifecycle of a bot's turn as
      //     trace messages (message_type: thinking | progress | tool_output) followed by
      //     a final `response`. Traces belong under the thread, so we only emit one when
      //     answering in-thread. A real agent emits many; we emit one to show the shape.
      await postTrace(event.id, 'thinking', 'Composing an echo…');
      await recordActivity(run, 'tool_call');
    }

    // (e) Simulate "thinking" so typing reads naturally — and so there's time to cancel.
    //     A real agent is genuinely busy here (model streaming, tools running) and would
    //     poll run.cancelled between steps the same way.
    const completed = await abortableSleep(thinkMs, run);
    if (!completed || run?.cancelled) {
      console.log('[proc] turn cancelled before answering — skipping reply');
      return; // server already marked the process killed
    }

    // (f) The answer.
    if (useThread) {
      await reply(event.id, `Echo: ${event.content}`);
    } else {
      await postToChannel(event.channelId, `Echo: ${event.content}`);
    }
    await finishRun(run, 'done');
  } catch (err) {
    await finishRun(run, 'error');
    throw err;
  } finally {
    runs.delete(run?.processId ?? '');
    // (g) Stop typing and mark the channel read up to here, mirroring a human client.
    wsSend(conn, { type: 'typing_stop' });
    await markRead(event.channelId).catch((e) => console.warn('[read]', errMsg(e)));
  }
}

// --- REST actions -----------------------------------------------------------
// POST /messages/:id/replies resolves the channel + thread root automatically.
// If :id is itself a reply, Threads attaches to the existing thread root.
async function reply(parentMessageId: string, content: string): Promise<Message> {
  const body: SendMessageRequest = {
    content,
    message_type: 'response', // final, user-visible bot answer
    metadata: { agent: BOT_USERNAME },
  };
  const msg = await api<Message>('POST', `/messages/${parentMessageId}/replies`, body);
  if (msg.id) myMessages.add(msg.id); // so we can detect humans reacting to our output
  console.log(`[reply] posted ${msg.id} in thread ${msg.threadId ?? parentMessageId}`);
  return msg;
}

// POST /channels/:id/messages posts a top-level message directly in the channel (no
// thread). Pass threadId in the body to attach to an existing thread instead.
async function postToChannel(channelId: string, content: string): Promise<Message> {
  const body: SendMessageRequest = {
    content,
    message_type: 'response', // final, user-visible bot answer
    metadata: { agent: BOT_USERNAME },
  };
  const msg = await api<Message>('POST', `/channels/${channelId}/messages`, body);
  if (msg.id) myMessages.add(msg.id);
  console.log(`[reply] posted ${msg.id} in channel ${channelId}`);
  return msg;
}

// A non-final trace message (thinking | progress | tool_output). Clients render these
// distinctly from the final answer; they exist so a slow agent can narrate its turn.
async function postTrace(parentMessageId: string, type: MessageType, content: string): Promise<void> {
  const body: SendMessageRequest = { content, message_type: type, metadata: { agent: BOT_USERNAME } };
  const msg = await api<Message>('POST', `/messages/${parentMessageId}/replies`, body);
  if (msg?.id) myMessages.add(msg.id);
}

// Add an emoji reaction. Idempotent server-side (re-adding the same emoji is a no-op).
async function react(messageId: string, emoji: string): Promise<void> {
  const body: AddReactionRequest = { emoji };
  await api('POST', `/messages/${messageId}/reactions`, body);
}

// Mark the channel read up to its latest message — clears the unread badge the same
// way the human client does when the bot "sees" a channel.
async function markRead(channelId: string): Promise<void> {
  await api('POST', `/channels/${channelId}/read`);
}

// --- Process lifecycle (REST) -----------------------------------------------
// Reconcile runs abandoned by a previous incarnation before this bot consumes new
// events. The endpoint is self-scoped by the bot token and is safe to repeat.
async function cleanupInterruptedRuns(): Promise<void> {
  try {
    const result = await api<{ cleaned: number; process_ids: string[] }>('POST', '/processes/cleanup-by-bot');
    if (result.cleaned > 0) {
      console.log(`[proc] marked ${result.cleaned} interrupted run(s) restarted`);
    }
  } catch (err) {
    // Process tracking is best-effort instrumentation; a transient cleanup failure
    // should not keep the bot offline. The server's age-based sweep remains a fallback.
    console.warn('[proc] could not reconcile interrupted runs:', errMsg(err));
  }
}

// Register a run with Threads so it appears on the process management page and can be
// cancelled. Returns a tracked InflightRun, or null if creation failed (the turn still
// proceeds — process tracking is best-effort instrumentation, not a hard dependency).
async function startRun(channelId: string, messageId: string): Promise<InflightRun | null> {
  try {
    const { id } = await api<{ id: string; status: string }>('POST', '/processes', {
      channel_id: channelId,
      message_id: messageId,
    });
    const run: InflightRun = { processId: id, channelId, cancelled: false, wake: () => {} };
    runs.set(id, run);
    console.log(`[proc] started ${id}`);
    return run;
  } catch (err) {
    console.warn('[proc] could not create process:', errMsg(err));
    return null;
  }
}

// Increment a tool-call/reply counter or add token usage as the turn progresses.
async function recordActivity(run: InflightRun | null, type: 'tool_call' | 'reply' | 'token_usage'): Promise<void> {
  if (!run) return;
  try {
    await api('POST', `/processes/${run.processId}/activity`, { type });
  } catch (err) {
    console.warn('[proc] activity failed:', errMsg(err));
  }
}

// Mark the run terminal. On cancel the server already set it to `killed`, so we only PATCH
// the happy-path statuses; we always drop our local tracking.
async function finishRun(run: InflightRun | null, status: 'done' | 'error'): Promise<void> {
  if (!run) return;
  runs.delete(run.processId);
  if (run.cancelled) return; // already killed server-side
  try {
    await api('PATCH', `/processes/${run.processId}`, { status, reply_count: 1 });
    console.log(`[proc] ${run.processId} → ${status}`);
  } catch (err) {
    console.warn('[proc] finish failed:', errMsg(err));
  }
}

// --- Helpers ----------------------------------------------------------------
function required(name: string): string {
  const v = process.env[name];
  if (!v) {
    console.error(`Missing required env var: ${name} (see .env.example)`);
    process.exit(1);
  }
  return v;
}

function errMsg(err: unknown): string {
  return err instanceof Error ? err.message : String(err);
}

function loadDotEnv(): void {
  try {
    const envPath = join(dirname(fileURLToPath(import.meta.url)), '..', '.env');
    for (const line of readFileSync(envPath, 'utf8').split('\n')) {
      const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*)\s*$/);
      if (m && !process.env[m[1]]) process.env[m[1]] = m[2];
    }
  } catch {
    // No .env file — rely on the real environment.
  }
}

// --- Webhook receiver (optional second transport) ---------------------------
// Cancellation reaches the bot over the channel WebSocket by default (see route()).
// Threads ALSO delivers the same events to any webhook URL the bot registered (POST
// /users/me/webhooks), so an agent that isn't holding sockets can still be cancelled.
// This is gated on THREADS_WEBHOOK_PORT and is purely a demonstration of that path: set
// the port, expose it to Threads (a tunnel in local dev), register the URL, and put the
// webhook's signing secret in THREADS_WEBHOOK_SECRET to verify signatures.
function startWebhookReceiver(): void {
  const port = Number(process.env.THREADS_WEBHOOK_PORT);
  if (!port) return; // not configured — WS is the only cancel transport
  const secret = process.env.THREADS_WEBHOOK_SECRET ?? '';

  const server = createServer((req, res) => {
    if (req.method !== 'POST') {
      res.writeHead(405).end();
      return;
    }
    const chunks: Buffer[] = [];
    req.on('data', (c: Buffer) => chunks.push(c));
    req.on('end', () => {
      const raw = Buffer.concat(chunks).toString('utf8');
      // Verify the HMAC signature when a secret is configured. Signed value is
      // `${timestamp}.${rawBody}` (see api/src/lib/webhooks.ts).
      if (secret) {
        const timestamp = req.headers['x-threads-timestamp'];
        const provided = String(req.headers['x-threads-signature'] ?? '').replace(/^sha256=/, '');
        const expected = createHmac('sha256', secret).update(`${timestamp}.${raw}`).digest('hex');
        const ok = provided.length === expected.length &&
          timingSafeEqual(Buffer.from(provided), Buffer.from(expected));
        if (!ok) {
          console.warn('[webhook] bad signature — rejecting');
          res.writeHead(401).end();
          return;
        }
      }
      // Acknowledge with any 2xx so Threads marks the delivery done.
      res.writeHead(204).end();
      try {
        const env = JSON.parse(raw) as { type?: string; data?: { type?: string; processId?: string } };
        if (env.data?.type === 'process_kill' && env.data.processId) {
          console.log(`[webhook] process_kill ${env.data.processId}`);
          markCancelled(env.data.processId);
        }
      } catch {
        // ignore non-JSON bodies
      }
    });
  });
  server.listen(port, () => console.log(`[webhook] receiver listening on :${port}`));
}

// --- Boot -------------------------------------------------------------------
await cleanupInterruptedRuns(); // close abandoned runs before consuming events
await advertiseCapabilities();
startWebhookReceiver(); // optional: also accept cancellation over webhooks (see above)
connectPresence(); // hold the presence socket open → the bot shows as online
await syncSubscriptions(); // startup sweep: no backfill, so a restart doesn't re-echo history
if (conns.size === 0) {
  console.log('[sync] not a member of any channel yet — will keep polling for invites/DMs');
}
const discovery = setInterval(
  // Re-discovery picks up channels/DMs joined at runtime — backfill so the first
  // message in a new ephemeral channel or DM still gets a reply.
  () => syncSubscriptions({ backfill: true }).catch((e) => console.warn('[sync]', errMsg(e))),
  DISCOVERY_INTERVAL_MS,
);

// --- Shutdown ---------------------------------------------------------------
process.on('SIGINT', () => {
  console.log('\n[bot] shutting down');
  clearInterval(discovery);
  presenceClosed = true;
  clearInterval(presenceKeepalive);
  presenceWs?.close();
  for (const conn of conns.values()) {
    conn.closed = true;
    clearInterval(conn.keepalive);
    conn.ws?.close();
  }
  process.exit(0);
});
